name: Ayrshire Gridiron
favicon: null
layout_spectrum: 1
typography_spectrum: 0.12958
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0c0c0e'
    - '#7a8080'
    - '#a01e1c'
    - '#d8c1d5'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.4375
  rhythmicContrast: 0.6505954372696579
purpose: []
